name: ftest auto tests
tests:
  - name: Basic help execution
    type: command
    command: ./ftest -h
    expected:
      return_code: 0
      stderr: ''
  - name: Invalid option
    type: command
    command: ./ftest --invalid_option
    expected:
      return_code: 2
  - name: Directory argument (with trailing slash)
    type: command
    command: ./ftest ./tests/
    expected:
      return_code: 0
  - name: Directory argument (without trailing slash)
    type: command
    command: ./ftest ./tests
    expected:
      return_code: 0
  - name: File argument (short form)
    type: command
    command: ./ftest -f ./tests/.dummy_ftest.yml
    expected:
      return_code: 0
  - name: File argument (long form)
    type: command
    command: ./ftest --file ./tests/.dummy_ftest.yml
    expected:
      return_code: 0
  - name: Directory and file arguments combined
    type: command
    command: ./ftest --file .dummy_ftest.yml ./tests
    expected:
      return_code: 0
  - name: Empty file
    type: command
    command: ./ftest --file .empty_file.yml ./tests
    expected:
      return_code: 3
  - name: Empty tests
    type: command
    command: ./ftest --file .empty_ftest.yml ./tests
    expected:
      return_code: 0
  - name: Failing tests
    type: command
    command: ./ftest --file .failing_ftest.yml ./tests
    expected:
      return_code: 1
  - name: Test suite name in header
    type: command
    command: ./ftest --file .named_suite_ftest.yml ./tests | head -n 1
    expected:
      return_code: 0
      stdout: "Tests results for suite 'Named ftest suite':\n"
  - name: Output format testing with passed and failed tests
    type: command
    command: ./ftest --file .output_testing_ftest.yml ./tests
    expected:
      return_code: 1
      stdout: "Tests results:\n----- Passing test -----\nPassed\n----- Another passing test -----\nPassed\n----- Failing test -----\nFailed\nWrong stdout: Expected 'success\n' but got 'failure\n'\n\n3 tests run. 2 passed. 1 failed.\n"
      stderr: ""
